### ISSUE TITLE
jump start should "error" if their are not enough nodes in the network

### ISSUE THREAD

**Issue by frankiebee** [entropyxyz/entropy-core#1112]
if their are only two nodes in the network jump start never finishes. If the intent is to just keep trying to jumpstart for ever (or until enough nodes join) a event for not enough nodes would be greatly appreciated so we can cut are tests otherwise they hang for ever.

**Comment by JesseAbram** [comment]
So we do have a not enough validators to start a network error [here](https://github.com/entropyxyz/entropy-core/blob/master/pallets/registry/src/lib.rs#L230)

In the case this is handled in a running network we may end up reporting and moving to slashing. But the retry method is already available and it is a graceful error that will let us try again. As well if all non running TSS were selected there would be no method for the chain to know this happened. 

Making the network more friendly to running sdk tests is not really in the scope of core and I suggest following how we handle that failure by allowing a retry X block into it (In your case to shut the test down X blocks into it......but furthermore probably running the right amount of TSSs)

**Comment by frankiebee** [comment]
running only two nodes in the network i'm not seeing the event 'NotEnoughValidatorsForJumpStart' after two minutes but am seeing `StartedNetworkJumpStart`.

**Comment by frankiebee** [comment]
is `NotEnoughValidatorsForJumpStart ` supposed to show up in system events?

**Comment by JesseAbram** [comment]
No, you are misunderstanding when you run two validators you aren't running a network that has two validators, you are running a network that has 4 validators and neglecting two of them, eventually they would get slashed and booted, there is no longer a two node network as that won't work in our system of a min 2 t and 3 n with 1 relayer network. 

In that case where there are validators but they are "offline" when they are selected to do a jumpstart, they will fail and the network allows a retry in X blocks. There would be no way to relay that information to the chain, the chain may one day undertake slashing and booting but that is another convo. 

We will not be writing code to allow the sdk to have an easier test in this scneneio

**Comment by mixmix** [comment]
@frankiebee you re-opened this. does the issue feel resolved or is it unresolved and needs more discussion?
