### ISSUE TITLE
No duplicate bytecode on chain

### ISSUE THREAD

**Issue by mixmix** [entropyxyz/entropy-core#1161]
> _:warning: This is likely an enhancement compared to other priorities. 
It's meant as a placeholder for a question/ optimization/ feature-request._

When you deploy a program, the `bytecode` gets saved on chain, along with the `configurationSchema` + `auxillaryDataSchema`. If I deploy another program which has the same `bytecode` but different schema, it would be ideal (for storage, cost etc) to not have another copy of the same `bytecode` on chain.

We're not sure how the current storage of blobs works on chain, so this may not be relevant. 

cc @frankiebee (we discussed this)

**Comment by JesseAbram** [comment]
I mean the idea is to add that to the hash to not let people send bad data and squat on bytecode that doesn't work, but this seems out of place here and should go into the config/aux data spec because why discuss if this makes sense if we don't even think we are gonna keep those fields on chain?
