### ISSUE TITLE
Add JSON output to select entropy-test-cli commands

### ISSUE THREAD

**Issue by cooldracula** [entropyxyz/entropy-core#1163]
_Why is this issue relevant?_

The entropy-test-cli is really useful in DevOps' ansible scripts for starting up a network and running basic smoke tests so we can run through the same [release checklist](https://github.com/entropyxyz/entropy-core/blob/23946aa2dd56e78a37d7fe78d0e3c5c5a132fef8/RELEASE_CHECKLIST.md#release-branch-and-local-network-checks) as core, but on staging infrastructure.

It would be easier to automate these steps if there was JSON output for the relevant commands.  This would let us reliably check that a command succeeded and assert our smoke tests are passing.  

_What steps are required to resolve this?_

JSON Output in entropy-test-cli for the following commands :
- status
   - i.e a success status if network is reachable and active. 
- jumpstart-network
   - i.e. a success status once network is jumpstarted. Bonus would be an error status plus message if there was an issue.  
- register
  - a success status and the verifying key
- sign
  - a success status and the transaction details

_Does this change the spec? HTTP, extrinsic, or storage? Is it breaking? Clearly describe the new interface._

It does not.

**Comment by ameba23** [comment]
This is underway.

Worth noting though that you can already programmatically determine whether a command was successful or not with the process exit status code.  All commands will exit with 0 on success and 1 on failure.  So for commands like jumpstart, update-programs, remove-program, etc, which do not give you any information in the happy case, this should already be enough to use in a script.

**Comment by ameba23** [comment]
@cooldracula this will get closed when i merge the PR, but please re-open if something else is needed, specifically:
- If you need a published (crates.io) version of the cli
- If you need to do different things in a script depending on the error type.  We could give different exit codes.
- If you need to be able to get details of the validators / TSS nodes (this would be easy to add).
- If you need to be able to get the current jumpstart status. Separate issue, but just so you are aware - sometimes i have found that the jumpstart command errors with a timeout, but the network eventually does jumpstart.
