### ISSUE TITLE
Free transaction terminology

### ISSUE THREAD

**Issue by fjarri** [entropyxyz/entropy-core#202]
An electricity-themed terminology has been introduced in #194 for free transactions. We need to take a second look at it and make sure that we don't overdo the metaphors, and if we use some, they are actually useful.

The concepts that we need the terms for (do correct me if my understanding is wrong):
1. A right to perform a single transaction. Current term - **cell**.
2. A token that can be spent to yield one **cell**. Current term - **zap**.
3. A token that can be spent once per era to yield one **cell**. Current term - **battery**.
4. The economics that uses **cells** (to use for e.g. naming the pallet). Current term - **electricity**.
5. Derivatives of **electricity**: `ElectricalAccount` (a map of users to their stats involving **electricity** usage), `ElectricalPanel` (the corresponding stats, the amount of tokens and their previous usage), `ElectricityMeter` (previous usage stats).

**Comment by HCastano** [comment]
We're not using this free transaction pallet anymore.
