### ISSUE TITLE
Blind user constraints on-chain via storing a hash

### ISSUE THREAD

**Issue by jakehemmerle** [entropyxyz/entropy-core#244]
@fjarri  suggested we store the hash of the user's constraints on-chain instead of the plaintext constraints for privacy purposes.

There are two main ways this would go:

- **User's store their constraints**: If the user doesn't backup the constraints, they need to get their constraint key out again and set new constraints from scratch. Constraints are still revealed to validators in signing party.
- **Server stores the user's constraints asymmetrically encrypted** - prevents the user from having to reset their constraints if they lose the preimage. Constraints are still revealed to validators in signing party.

We could still somewhat blind the active constraints by updating the on-chain hash every time we do a signing request and using a nonce in the constraint's preimage, but this requires the constraint key every time we want to send a tx.

While this would be a good way of keeping the constraints being visible on-chain, there seem to be a ton of unresolved issues in practice.

**Comment by HCastano** [comment]
Closing since we have no plans to address this soon. If this comes up again we can re-open the issue.
