### ISSUE TITLE
Basic Benchmarking/Profiling

### ISSUE THREAD

**Issue by jakehemmerle** [entropyxyz/entropy-core#323]
Would be good to get some basic benchmarking down so we can track things over time. This would be great to do before we switch to something like Axum, should we choose to do so. Shouldn't take took long.

[The Rust Performance Book](https://nnethercote.github.io/perf-book/benchmarking.html) is a good spot to start. [criterion](https://github.com/bheisler/criterion.rs) is probably the way to go, since it's very widely supported, a little more feature filled if we need it going forward. Rust's built-in benchmarking relies on nightly.

**Comment by HCastano** [comment]
Yeah we should have more benchmarks, but we have no plans to address this any time soon. Will open new issues when we do.
