### ISSUE TITLE
Consider using WebRTC as transport for signing protocol messages

### ISSUE THREAD

**Issue by ameba23** [entropyxyz/entropy-core#366]
This was proposed by Jake.

We discussed using websockets for protocol messages and they have two limitations:
- We can't create TLS over Websocket (wss) connections from the browser without having a certificate from a certificate authority.
- We can make browser-to-server connections but not browser-to-browser connections. So the only way two users can communicate with each other would be by relaying messages through a server.

WebRTC enables direct browser-to-browser connections.

Libp2p has a ['webRTC Direct'](https://github.com/libp2p/specs/blob/master/webrtc/webrtc-direct.md) protocol which specifically aims to address the issue of needing trusted TLS certificates. This uses TLS as well as [noise](https://noiseprotocol.org/noise.html), so everything is encrypted twice. The reasoning for this is that 'TLS provides confidentiality and integrity but not authenticity'.

The rust implementation of Libp2p does include [WebRTC but the docs are not great](https://docs.rs/libp2p-webrtc/latest/libp2p_webrtc/index.html).

[`webrtc-rs`](https://github.com/webrtc-rs/webrtc), which libp2p uses internally has [this example showing making communication with a browser using data-channels](https://github.com/webrtc-rs/webrtc/tree/master/examples/examples/data-channels) - which i recommend trying out as it make it easy to see how the signalling needed to set up a connection works.

To initiate a WebRTC connection from the browser to a threshold server:
- We get our public IP from a public STUN server such as `stun.l.google.com` and use it to make a Session Description Protocol (SDP) 'offer' message. This all done by the JS [`RTCPeerConnection`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection) API.
- We could send the SDP 'offer' message in an HTTP request to the threshold server.
- The threshold server could respond with an SDP 'answer' message with its own connection details (by calling [`RTCPeerConnection::create_answer`](https://docs.rs/webrtc/0.8.0/webrtc/peer_connection/struct.RTCPeerConnection.html#method.create_answer)).
- The browser client calls [`RTCPeerConnection.setRemoteDescription`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setRemoteDescription) with the answer message, and a data connection is initiated.
- Data channels are named, so we could have one data channel per protocol session, and give them a unique name (eg: based on the message hash).

[`snow`](https://docs.rs/snow/0.9.2/snow), the NOISE implementation used by Libp2p is also very well documented.

I don't know whether it would be easier to use libp2p, or to implement noise over webrtc ourselves.

**Comment by HCastano** [comment]
We're not looking into this anymore, can re-open if this becomes relevant again.
