### ISSUE TITLE
Session randomness choice

### ISSUE THREAD

**Issue by fjarri** [entropyxyz/entropy-core#375]
PR #367 introduces shared randomness parameter for signing sessions, a seed that will in particular influence the session ID of the protocol messages. For now it is hardcoded, so all the messages will have the same session ID, which naturally only works for tests.

The details of selecting the randomness will depend on how exactly the signing process is initiated. The randomness must be:
- The same for all participating nodes,
- Different for the sessions that may be running at the same time with the same node

Ideally, the randomness should also be *globally* unique, and derived from some globally verified randomness (e.g. the block hash) which will simplify the possible conflict resolution process where a third party would have to inspect the messages and verify that they belong to the right session. We will have to think about that.

**Comment by HCastano** [comment]
Closed in #687.
