### ISSUE TITLE
`server` test `test_store_share` fails occasionally in CI

### ISSUE THREAD

**Issue by ameba23** [entropyxyz/entropy-core#466]
This is from a conversation on discord in September that i should probably have made into an issue then.

Occasionally the test_store_share test fails in CI. Here is an example: https://app.circleci.com/pipelines/github/entropyxyz/entropy-core/1627/workflows/1d989818-e294-4a2e-990c-09a774abdadd/jobs/6377  

I will try to find a more recent example.

This happens rarely, and on re-running the pipeline is usually passes. 

## Why is this issue relevant?

We want CI to pass consistently

## What steps are required to resolve this?

My hunch was that it was related to a timeout for the http request made by the propagation pallet.

From a message in discord:

> regarding the `test_store_share` test which occasionally fails that i was going on about. I think it might be related to the http request 'deadline' of 2 seconds set in the propagation pallet. The `user/new` endpoint doesn't give a response until after DKG is completed, and it might be that if the request gets aborted because of this timeout, axum stops the running task. Im not totally sure i've got this right, but since it also effects the test im currently writing it will hopefully become clearer whats going on and i'll put up a card explaining what needs fixing.

Here is where that timeout gets set:
https://github.com/entropyxyz/entropy-core/blob/357477b8acf9fcc7f532efea789c326485baf863/pallets/propagation/src/lib.rs#L71

However I did at some point try increasing this an still had this problem, so it could be something else.  I will try to find the discussion on that, i think it was in a PR. 

## Does this change the spec? HTTP, extrinsic, or storage? Is it breaking? Clearly describe the new interface.

I think it should be possible to fix this without a breaking change.

**Comment by ameba23** [comment]
I know this issue is probably going to go away once the tofino stuff is finished.

But just for the record this happened again today in CI: https://app.circleci.com/pipelines/github/entropyxyz/entropy-core/4960/workflows/817e94da-4f53-4b5f-899f-684a5b7a5e05/jobs/18646

**Comment by HCastano** [comment]
Closing since this test was removed in https://github.com/entropyxyz/entropy-core/pull/1026.
