### ISSUE TITLE
Fix Partition all keys function 

### ISSUE THREAD

**Issue by JesseAbram** [entropyxyz/entropy-core#510]
Currently partition_all_keys in #504 takes a rotating batch of all keys for a proactive refresh. This is done to not have a proactive refresh have to refresh the whole network as that could cause undo stress on validators partaking

This works for when registered keys are small but as they grow and as keys get inserted and ordered the algorithim doesn't really handle the ordering. It will just take keys in position from ex. 0-10 in the DB, then next refresh from 10-20 etc with no consideration of when and where those keys were inserted. 

### possible solutions 
 * storing a last refresh time (would require an extra rpc call per refresh and a call by a validator back into the chain)
 * having the algorithim also take into account the ordering of the kvdb (like take a batch of keys with the second letter of the address as a then b etc)

**Comment by HCastano** [comment]
This isn't relevant anymore after https://github.com/entropyxyz/entropy-core/issues/941.
