### ISSUE TITLE
Add Proactive Refresh trigger in 

### ISSUE THREAD

**Issue by JesseAbram** [entropyxyz/entropy-core#511]
Proactive Refresh trigger was removed in #453 and should be added in, when we feel ready and stable to introduce it into our network

### To add in 
* refresh counter (just increment the refresh counter by REFRESHES_PRE_SESSION) 
* Proactive refresh now takes in an array of validator info

**Comment by HCastano** [comment]
We're moving away from refreshes to reshares, so closing.
