### ISSUE TITLE
Convert user constraint to Pointer 

### ISSUE THREAD

**Issue by JesseAbram** [entropyxyz/entropy-core#531]
* User's will not set constraints at register, rather they will point to an already set constraint 
* They can pre set it or choose it 
* The storage of programs will use the hash of the bytecode as the key

## Next Steps
* The registered struct will hold the pointer which will be a string for now but can be converted to a bounded vec when we implement program linking
*  A global struct controlled by some form of governance (this will be free storage and won't be able to get pulled, plus it will be more vetted)

**Comment by HCastano** [comment]
This was closed a while ago.
