### ISSUE TITLE
TSS server's `test_store_share` occasionally fails in CI with keyshare mismatch

### ISSUE THREAD

**Issue by ameba23** [entropyxyz/entropy-core#635]
Occasionally in CI `test_store_share` fails with:
```
thread 'user::tests::test_store_share' panicked at crates/threshold-signature-server/src/user/tests.rs:640:5:
assertion `left != right` failed
```

See the failure in CI here: https://app.circleci.com/pipelines/github/entropyxyz/entropy-core/3173/workflows/ebe689da-3660-4093-9c51-ddb1a8f57701/jobs/11114

This came up in this PR https://github.com/entropyxyz/entropy-core/pull/634 

Looking at the test, this will always happen if the registration takes longer than 10 seconds to complete:
https://github.com/entropyxyz/entropy-core/blob/0b8bda921ca90b579f090dea6e19cd5c809515ee/crates/threshold-signature-server/src/user/tests.rs#L622

So one way to address this would be to increase the timeout from 10 seconds to say 30 seconds.

**Comment by HCastano** [comment]
This test was removed in https://github.com/entropyxyz/entropy-core/pull/1026.
