### ISSUE TITLE
`/user/receive_key` endpoint can be misused by a malicious validator

### ISSUE THREAD

**Issue by ameba23** [entropyxyz/entropy-core#652]
During registration or proactive refresh a malicious validator could send other members of their subgroup bad data over the [`/user/receive_key`](https://github.com/entropyxyz/entropy-core/blob/fe96ae423dcf3e333833220dd1d97757c1450069/crates/threshold-signature-server/src/user/api.rs#L374) endpoint.

There are a number of nasty things that could happen here:

## Write access to mnemonic and secret key

First and foremost, when reading keyshares in `sync_kvdb`, we check the key against [`FORBIDDEN_KEYS`](https://github.com/entropyxyz/entropy-core/blob/fe96ae423dcf3e333833220dd1d97757c1450069/crates/threshold-signature-server/src/helpers/launch.rs#L50) which include the mnemonic, and x25519 secret. No such check happens in `receive_key`, which means the validator can delete the mnemonic and secret encryption key of all validators in its subgroup, causing them to be unable to send transactions or decrypt messages.

We can mitigate this by adding a similar forbidden keys check, or storing the mnemonic etc in a separate namespace to keyshares. 

## Can overwrite legitimate keyshares with garbage

Sending a bad keyshare to another member of the subgroup will likely cause them to get slashed next time they participate in signing message, even though it was not their fault.

Worse still, sending bad keyshares to all other members of the subgroup, causing them to delete their legitimate keyshares, means the malicious validator now holds the only copy of that that share and can hold the user's account to ransom.  

This is the hardest one to fix, but there are some basic checks we could do to make this attack much harder.  Eg: storing old keyshares until we have successfully signed a message with the new one, and checking the validating key of the keyshare.

## Can fill other validator's disks with garbage

There are currently no checks on the size of the payload, and unknown keys will always be accepted.  This means the endpoint can repeatedly be called with as much data as fits in an HTTP post request until the validator's disk becomes full.

This could be mitigated by checking whether the given key is a registered or registering account even if it does not currently existing in the database currently, and adding a payload size limit or checking that the payload can be deserialized to a keyshare.

**Comment by HCastano** [comment]
This endpoint was removed in https://github.com/entropyxyz/entropy-core/issues/941.
