### ISSUE TITLE
program_modfication_key to root_key?

### ISSUE THREAD

**Issue by frankiebee** [entropyxyz/entropy-core#670]
with the (possible) removal of the sig request key we @JesseAbram and i did briefly discuss in Hawaii the possible rename of program_modification_key to root_key or some other name. Does any one have option on this? Do we just leave it as program_modification_key? etc.

**Comment by HCastano** [comment]
@frankiebee `root_key` already has a specific meaning in the world of Substrate, so this wouldn't be a good name for it. We think that `program_modification_account` describes things pretty well.

It would be nice if the SDK and Core could agree on the same name though.
