### ISSUE TITLE
Make entropy-protocol's integration test into a benchmark

### ISSUE THREAD

**Issue by ameba23** [entropyxyz/entropy-core#783]
I attempted to make a benchmark for running the signing protocol (and eventually DKG and proactive refresh) with an arbitrary number of parties in order to inform the subgroups design.

Doing this using [criterion](https://docs.rs/criterion) worked for me locally but others had issues with it and in the end i abandoned the PR - see https://github.com/entropyxyz/entropy-core/pull/738#discussion_r1569098163

It would be great to resolve this issue and have a statistical benchmark which we can use to optimise the protocol.

**Comment by HCastano** [comment]
Will revisit this at some point when we decide to dig deeper into performance metrics.
