### ISSUE TITLE
`entropy-tss` should no longer be a library crate 

### ISSUE THREAD

**Issue by ameba23** [entropyxyz/entropy-core#802]
Merging https://github.com/entropyxyz/entropy-core/pull/775 means integration tests no longer need entropy-tss as a dependency, and it does not need to be a library crate.

The advantage of turning it back into a binary crate is the full API will be documented when we publish the crate, not just the public parts exposed in the library, which following https://github.com/entropyxyz/entropy-core/pull/775 is basically nothing.

**Comment by HCastano** [comment]
@ameba23 doesn't think this is relevant anymore.
