### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by ok-john** [entropyxyz/entropy-core#849]
Why is this issue relevant?
Hey hope you're all doing well - I was looking to run a node and try out the test net. I saw the links to the entrosplainer and API docs are broken on the entropy github main page (https://github.com/entropyxyz/.github/blob/main/profile/README.md) 
<img width="1204" alt="Screenshot" src="https://github.com/entropyxyz/entropy-core/assets/63182053/28bc456e-630f-4cf0-9a40-a522b74260e3">

What steps are required to resolve this?

Does this change the spec? HTTP, extrinsic, or storage? Is it breaking? Clearly describe the new interface.

**Comment by ameba23** [comment]
Hey! Thanks for this.  Will fix...
