### ISSUE TITLE
`entropy-tss` test setup should use at least 3 nodes for t-of-N testing

### ISSUE THREAD

**Issue by ameba23** [entropyxyz/entropy-core#858]
Explaination here: https://github.com/entropyxyz/entropy-core/pull/800#issuecomment-2130270112

See also: https://github.com/entropyxyz/entropy-core/issues/859 as decision 4 effects what would be a good test setup.

**Comment by HCastano** [comment]
Related issue 892

**Comment by ameba23** [comment]
Closing as completed
