### ISSUE TITLE
Add Faucet Test back in

### ISSUE THREAD

**Issue by JesseAbram** [entropyxyz/entropy-core#909]
Currently the algorithim to pick subgroup signers is causing the faucet test to fail, because the message requires a blocknumber that changes the selection message. So as of now the test it ignored (although it can be fixed with some hacks or another test network config which would be a lot of code) we are removing subgroups soon so this should just resolve itself and we can unignore the test

**Comment by HCastano** [comment]
Since subgroups have been removed we should be able to get a PR open to fix this @JesseAbram.
