### ISSUE TITLE
Rename the `entropy` binary 

### ISSUE THREAD

**Issue by frankiebee** [entropyxyz/entropy-core#964]
A discussion about the core binary name was started in this [issue on the cli](https://github.com/entropyxyz/cli/issues/198) and i didn't want it to get lost putting it here so y'all can continue it in the appropriate repo.

**Comment by ameba23** [comment]
Pasting a comment from an old PR relating to this:
>     Since the name entropy is taken on crates.io, we need to rename entropy to entropy-node or similar. Ideally we want to keep the binary name as entropy, otherwise we have a big task of changing various scripts, CI scripts, dockerfiles, etc. I wanted to do that in this PR, but i found that the cargo feature to have a different binary name is only available on cargo nightly, so doing that will also require some changes to CI scripts, etc. See: https://doc.rust-lang.org/cargo/reference/unstable.html#different-binary-name

**Comment by HCastano** [comment]
Gonna close this for now, will revisit if we decide to publish the node to crates.io.
