### ISSUE TITLE
Confusion around constants for t and n

### ISSUE THREAD

**Issue by ameba23** [entropyxyz/entropy-core#969]
`entropy-shared` has the following constants:
https://github.com/entropyxyz/entropy-core/blob/f712a8524e2d0ab1b0598fcc727c36f00e5b154c/crates/shared/src/constants.rs#L36

https://github.com/entropyxyz/entropy-core/blob/f712a8524e2d0ab1b0598fcc727c36f00e5b154c/crates/shared/src/constants.rs#L67

https://github.com/entropyxyz/entropy-core/blob/f712a8524e2d0ab1b0598fcc727c36f00e5b154c/crates/shared/src/constants.rs#L70

`SIGNING_PARTY_SIZE` is used by the registry pallet to check we have the right number of confirmations following network DKG.

But i would expect this to be 3, not 2.  I think it would be good to have just two constants to avoid confusion.

**Comment by JesseAbram** [comment]
yes Signing party size should be replaced by total signers and signer threshold, will add this to #941

**Comment by ameba23** [comment]
Fixed in https://github.com/entropyxyz/entropy-core/pull/971
